#!/command/with-contenv bash
set -euo pipefail
mkdir -p /run/redis /data/redis
chown -R redis:redis /run/redis /data/redis
exec gosu redis redis-server --save 900 1 --dir /data/redis --unixsocket /run/redis/redis.sock --unixsocketperm 777 --port 0 --protected-mode yes
